export const FETCH_GAMES = 'fetchGames'
export const FETCH_GAME = 'fetchGame'
export const FETCH_INFO = 'fetchInfo'
export const FETCH_CAPACITY = 'fetchCapacity'
export const FETCH_PING = 'fetchPing'
export const DELETE_GAME = 'deleteGame'
export const UPDATE_GAME = 'updateGame'
export const UPDATE_GAMES = 'updateGames'
